spring:
  datasource:
    url: jdbc:mysql://localhost:3306/streamdb?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect:
          storage_engine: innodb

server:
  port: 8080

logging:
  level:
    com.example.streaming: DEBUG
    org.springframework.web: INFO
